name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch like 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Replace Firebase Config Placeholders
        run: |
          sed -i "s/%%FIREBASE_API_KEY%%/${{ secrets.FIREBASE_API_KEY }}/g" index.html
          sed -i "s/%%FIREBASE_AUTH_DOMAIN%%/${{ secrets.FIREBASE_AUTH_DOMAIN }}/g" index.html
          sed -i "s/%%FIREBASE_PROJECT_ID%%/${{ secrets.FIREBASE_PROJECT_ID }}/g" index.html
          sed -i "s/%%FIREBASE_STORAGE_BUCKET%%/${{ secrets.FIREBASE_STORAGE_BUCKET }}/g" index.html
          sed -i "s/%%FIREBASE_MESSAGING_SENDER_ID%%/${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}/g" index.html
          sed -i "s/%%FIREBASE_APP_ID%%/${{ secrets.FIREBASE_APP_ID }}/g" index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: main # Deploy directly to the main branch
          # If your GitHub Pages is served from /docs, use this instead:
          # publish_dir: .
          # destination_dir: docs
